---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: yourdockerhubusername/sample-app:latest
        ports:
        - containerPort: 8000
...
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: app1
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
...